// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sidecar/ner/ner.proto

package nerpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Optional: correlation ID for tracing
	RequestId     string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_sidecar_ner_ner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_ner_ner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_sidecar_ner_ner_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnalyzeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Start         int32                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_sidecar_ner_ner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_ner_ner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_sidecar_ner_ner_proto_rawDescGZIP(), []int{1}
}

func (x *Entity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Entity) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Entity) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Entity) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_sidecar_ner_ner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sidecar_ner_ner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_sidecar_ner_ner_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

var File_sidecar_ner_ner_proto protoreflect.FileDescriptor

const file_sidecar_ner_ner_proto_rawDesc = "" +
	"\n" +
	"\x15sidecar/ner/ner.proto\x12\x03ner\"C\n" +
	"\x0eAnalyzeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"g\n" +
	"\x06Entity\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x05R\x03end\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\":\n" +
	"\x0fAnalyzeResponse\x12'\n" +
	"\bentities\x18\x01 \x03(\v2\v.ner.EntityR\bentities2D\n" +
	"\n" +
	"NERService\x126\n" +
	"\aAnalyze\x12\x13.ner.AnalyzeRequest\x1a\x14.ner.AnalyzeResponse\"\x00B\x1bZ\x19sysMon/internal/pii/nerpbb\x06proto3"

var (
	file_sidecar_ner_ner_proto_rawDescOnce sync.Once
	file_sidecar_ner_ner_proto_rawDescData []byte
)

func file_sidecar_ner_ner_proto_rawDescGZIP() []byte {
	file_sidecar_ner_ner_proto_rawDescOnce.Do(func() {
		file_sidecar_ner_ner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sidecar_ner_ner_proto_rawDesc), len(file_sidecar_ner_ner_proto_rawDesc)))
	})
	return file_sidecar_ner_ner_proto_rawDescData
}

var file_sidecar_ner_ner_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sidecar_ner_ner_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: ner.AnalyzeRequest
	(*Entity)(nil),          // 1: ner.Entity
	(*AnalyzeResponse)(nil), // 2: ner.AnalyzeResponse
}
var file_sidecar_ner_ner_proto_depIdxs = []int32{
	1, // 0: ner.AnalyzeResponse.entities:type_name -> ner.Entity
	0, // 1: ner.NERService.Analyze:input_type -> ner.AnalyzeRequest
	2, // 2: ner.NERService.Analyze:output_type -> ner.AnalyzeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sidecar_ner_ner_proto_init() }
func file_sidecar_ner_ner_proto_init() {
	if File_sidecar_ner_ner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sidecar_ner_ner_proto_rawDesc), len(file_sidecar_ner_ner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sidecar_ner_ner_proto_goTypes,
		DependencyIndexes: file_sidecar_ner_ner_proto_depIdxs,
		MessageInfos:      file_sidecar_ner_ner_proto_msgTypes,
	}.Build()
	File_sidecar_ner_ner_proto = out.File
	file_sidecar_ner_ner_proto_goTypes = nil
	file_sidecar_ner_ner_proto_depIdxs = nil
}
